repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff  # Run the linter.
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format  # Run the formatter.
        types_or: [ python, pyi, jupyter ]
